### ISSUE TITLE
ブログタイトルとかが大きく表示できるといいのかも

### ISSUE THREAD

**Issue by fukayatsu** [fukayatsu/blog#18]

**Comment by taea** [comment]
₍₍:horse:

**Comment by taea** [comment]
こんな感じに
![image](https://cloud.githubusercontent.com/assets/341101/11204486/c22ea4c2-8d42-11e5-8ae0-43e6ccf4ab2e.png)

**Comment by fukayatsu** [comment]
おーよさげ
